name: Extract M3U8

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repo-nu klonla
      uses: actions/checkout@v3

    - name: Python quraşdır
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Chrome quraşdır
      uses: browser-actions/setup-chrome@v1

    - name: Asılılıqları quraşdır
      run: pip install -r requirements.txt

    - name: Skripti işə sal
      run: python extract_m3u8.py
